version: "3.9"
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile-dev
    env_file:
      - ./.env
    ports:
      - "80:80"
    volumes:
      - ./api/app:/app/app
    links:
      - mongo
  mongo:
    image: mongo:latest
    env_file:
      - ./.env
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./database/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh:ro
      - mongodb_data_container:/data/database

volumes:
  mongodb_data_container: