version: "3.9"
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile-dev
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./api/app:/app/app
    depends_on:
      - mongo
      - redis
    links:
      - mongo
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile-dev
    env_file: .env
    ports:
      - "3000:3000"
      - "49153:49153"
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
      - /usr/src/frontend/.next
  worker:
    build:
      context: ./api/
      dockerfile: Dockerfile-dev
    env_file: .env
    volumes:
      - ./api/app/celery:/app/app/celery
    links:
      - redis
    depends_on:
      - api
      - redis
    entrypoint: celery --app app.celery.celery_app worker -c 2 --loglevel=info
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file: .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
  mongo:
    image: mongo:latest
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - mongodb_data_container:/data/database

volumes:
  mongodb_data_container: