version: "3.9"
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile-dev
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "8080:8080"
    volumes:
      - ./api/app:/app/app
    links:
      - mongo
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile-dev
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
  mongo:
    image: mongo:latest
    env_file:
      - ./.env
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - mongodb_data_container:/data/database

volumes:
  mongodb_data_container: