FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8-alpine3.10

COPY ./requirements.txt /app
COPY ./.env /app

RUN apk add build-base libffi-dev
RUN pip install -r requirements.txt

COPY ./app /app/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--loop", "asyncio", "--debug", "--reload-dir", "/app"]